#!/bin/bash
function packageJar() {
    mvn -f /usr/app/pom.xml package -Dmaven.repo.local=/usr/.m2 -Dmaven.test.skip=$MVN_SKIP_TEST
    cp /usr/app/target/*.jar /usr/jar/app.jar
}

packageJar &

while true; do
    inotifywait -r -e close_write,modify,create /usr/app/src /usr/app/pom.xml
    for pid in $(ps -ef | awk '/java|cp/ {print $2}'); do kill -9 $pid; done
    packageJar &
done