#!/bin/bash

function packageJar() {
    PID=$(pidof java) && kill -9 $PID
    java -jar /usr/jar/app.jar
}

if [ -e "/usr/jar/app.jar" ]; then
    packageJar &
fi

while true; do
    inotifywait -r -e close_write,modify /usr/jar
    packageJar &
done