#!/bin/bash

function packageJar() {
    PID=$(pidof java) && kill -9 $PID
    java -jar /usr/jar/app.jar
}

packageJar &
while true; do
    inotifywait -r -e close_write,modify /usr/jar
    packageJar &
done